---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create a new EC2 instance
    ec2:
      key_name: VTestKey
      group: TestSecurityGroup-V
      instance_type: t2.micro
      image: ami-07dc0b5cad2999c28  # Basic AWS EC2 Image from the AMI store
      wait: yes
      region: us-west-2  # This is the LONDON region used for testing
      count: 1
      vpc_subnet_id: subnet-3cb07f70  # Change this to your desired subnet ID
      assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: launched
      with_items: "{{ ec2.instances }}"

    - name: Configure new instance
       hosts: launched
        become: yes
  tasks:
    - name: Update package cache and install Apache
      package:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started

    - name: Open port 80 (HTTP) in the security group
      ec2_group:
        name: sg-024b1836b3640207f # Replace with your security group name
        description: Allow HTTP traffic
        region: us-west-2  # Change this to your desired region
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Create HTML directory
      file:
        path: /var/www/html
        state: directory

    - name: Retrieve HTML file from GitHub
      get_url:
        url: https://github.com/Gronunder/WebPasswordGeneratorTest1/blob/main/PassGen.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Set ownership and permissions
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

    - name: Print message indicating Apache has been restarted
      debug:
        msg: "Apache has been restarted."  
