---
 - name:  provisioning EC2 instances using Ansible
   hosts: localhost
   connection: local
   gather_facts: False
   tags: provisioning

   vars:
     keypair: VTestKey
     instance_type: t2.small
     image: ami-07dc0b5cad2999c28  # Basic AWS EC2 Image from the AMI store
     wait: yes
     group: webserver
     count: 1
     region: us-west-2  # This is the LONDON region used for testing
     security_group: TestSecurityGroup-V
     vpc_subnet_id: subnet-3cb07f70  # Change this to your desired subnet ID
   
   tasks:
     - name: Task # 2 Launch the new EC2 Instance
       local_action:  ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
       register: ec2
     - name: Task # 3 Add Tagging to EC2 instance
       local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Name: WebServer1