---

- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_type: t2.micro
    ami: ami-07dc0b5cad2999c28  # Basic AWS EC2 Image from the AMI store
    region: us-west-2
    key_name: VTestKey
    security_group: TestSecurityGroup-V
    tag_name: WebServerID
    vpc_subnet_id: subnet-3cb07f70  # Change this to your desired subnet ID
  tasks:
    - name: Launch EC2 Instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        region: "{{ region }}"
        group: "{{ security_group }}"
        instance_tags:
          Name: "{{ tag_name }}"
        wait: true
      register: ec2

- name: Print Public IP Address
    debug:
      msg: "Instance IP address is {{ ec2_instance.instances[0].public_ip }}"