---
 - name:  provisioning EC2 instances using Ansible
   hosts: localhost
   connection: local
   gather_facts: False
   tags: provisioning

   vars:
     keypair: VTestKey
     instance_type: t2.small
     image: ami-07dc0b5cad2999c28  # Basic AWS EC2 Image from the AMI store
     wait: yes
     group: webserver
     count: 1
     region: eu-west-2  # This is the LONDON region used for testing
     security_group: TestSecurityGroup-V
     vpc_subnet_id: subnet-3cb07f70  # Change this to your desired subnet ID
   
   tasks:
     - name: Task # 2 Launch the new EC2 Instance
       community.aws.ec2_instance:  # Updated to 'community.aws.ec2_instance'
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image_id: "{{ image }}"
         security_groups: "{{ security_group }}"
         count: "{{ count }}"
         region: "{{ region }}"
         wait: "{{ wait }}"
         subnet_id: "{{ vpc_subnet_id }}"
       register: ec2

     - name: Tag the EC2 instance
       ec2_tag:
         region: "{{ region }}"
         resource: "{{ ec2_result.instances[0].id }}"
         state: present
         tags:
           Name: WebServer1
         with_items: "{{ ec2_result.instances }}"
