---
- name: Provisioning EC2 instances using Ansible
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    keypair: VTestKey
    instance_name: WebServer2
    instance_type: t2.small
    image: ami-07dc0b5cad2999c28  # Basic AWS EC2 Image from the AMI store
    region: eu-west-2  # This is the LONDON region used for testing
    security_group: TestSecurityGroup-V
    vpc_subnet_id: subnet-3cb07f70  # Change this to your desired subnet ID

  tasks:
    - name: Task #2 Launch the new EC2 Instance
      community.aws.ec2_instance:  # Updated to 'community.aws.ec2_instance'
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        security_groups: "{{ security_group }}"
        count: 1
        region: "{{ region }}"
        wait: yes
        subnet_id: "{{ vpc_subnet_id }}"
      register: ec2

    - name: Wait for the instances to be running
      community.aws.ec2_instance_info:
        instance_ids:
          - "{{ ec2.instances[0].id }}"
        region: "{{ region }}"
      register: ec2_info
      until: ec2_info.instances[0].state.name == 'running'
      retries: 30
      delay: 10

    - name: Install apache httpd using package module
      become: yes
      ansible.builtin.package:
        name: apache2  # On Ubuntu, it's apache2, not httpd
        state: present

    - name: Ensure httpd service is started and enabled
      become: yes
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Retrieve HTML file from GitHub
      get_url:
        url: https://raw.githubusercontent.com/Gronunder/WebPasswordGeneratorTest1/main/HTML/PassGen.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Set ownership and permissions on index.html
      file:
        path: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Apache service
      ansible.builtin.service:
        name: apache2
        state: restarted

    - name: Print message indicating Apache has been restarted
      debug:
        msg: "Apache has been restarted."
