---

- name: Task # 2 Launch the new EC2 Instance
  amazon.aws.ec2_instance:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image }}"
    security_groups: "{{ security_group }}"
    count: "{{ count }}"
    region: "{{ region }}"
    network:
      assign_public_ip: yes
    subnet_id: "{{ vpc_subnet_id }}"
    name: "{{ instance_name }}"
    wait: true
  register: ec2

- name: Tag EC2 instance
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ ec2.instance_ids[0] }}"
    state: present
    tags: "{{ instance_tag }}"


- name: Pause for 1 minute
  ansible.builtin.pause:
   minutes: 1

- name: Get information about the newly created instance
  amazon.aws.ec2_instance_info:
    region: eu-west-2
    filters:
      instance-state-name: running
      tag:Name: WebServer2
  register: ec2

- name: Add the instance to the host group
  ansible.builtin.add_host:
    hostname: "{{ ec2.instances[0]['network_interfaces'][0]['private_ip_address'] | default('') }}"
    groups:
      - my_webserver
