#This is only a template and it's not set at the moment. 


name: Update and Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-playbook -i localhost, playbook.yml

